FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Mount the code via volume, no need to copy in dev
COPY . .

EXPOSE 5173

# Run Vite dev server (or CRA dev)
CMD ["npm", "run", "dev"]
